---------------------------- WAREHOUSE CREATION
CREATE OR REPLACE WAREHOUSE TEST_WH 
WITH 
    WAREHOUSE_SIZE = XLARGE 
    AUTO_RESUME = TRUE 
    AUTO_SUSPEND = 300 
    MIN_CLUSTER_COUNT = 1 
    MAX_CLUSTER_COUNT = 10 
    COMMENT = 'TEST';


---------------------------- FILE FORMAT CREATION
CREATE OR REPLACE FILE FORMAT POC.SAIKOT_ROY.AZURE_CSV 
TYPE = 'CSV' 
FIELD_DELIMITER = ',' 
SKIP_HEADER = 1 
EMPTY_FIELD_AS_NULL = true 
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE  OR REPLACE FILE FORMAT POC.SAIKOT_ROY.AZURE_JSON 
TYPE = 'JSON';

CREATE  OR REPLACE FILE FORMAT POC.SAIKOT_ROY.AZURE_PARQUET
TYPE = 'parquet';

---------------------------- STAGE CREATION
CREATE OR REPLACE STAGE POC.SAIKOT_ROY.AZURE_EXT_STAGE 
URL = 'azure://sargsaikotroy01eastus.blob.core.windows.net/snowflake-data' 
credentials = (azure_sas_token = 'sv=2022-11-02&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2029-05-22T11:33:35Z&st=2024-05-22T03:33:35Z&spr=https&sig=iTn3GkGKmpCTM719as5RTLj2RYFMiyT9GwaOy4y1yng%3D');


---------------------------- LISTING FILES FROM STAGE
list @POC.SAIKOT_ROY.AZURE_EXT_STAGE;
desc stage POC.SAIKOT_ROY.AZURE_EXT_STAGE;


---------------------------- COPY DATA FROM AZURE BLOB TO SNOWFLAKE TABLE IN CSV
copy into POC.SAIKOT_ROY.EMPLOYEES
from '@POC.SAIKOT_ROY.AZURE_EXT_STAGE/employees.csv'
FILE_FORMAT = POC.SAIKOT_ROY.AZURE_CSV
VALIDATION_MODE = RETURN_5_ROWS;


---------------------------- COPY DATA FROM AZURE BLOB TO SNOWFLAKE TABLE IN JSON
copy into POC.SAIKOT_ROY.EMP
FROM (select
    $1:empId::string as empid,
    $1:fullName::string as fullName,
    $1:address::string as address,
    METADATA$FILENAME
from '@POC.SAIKOT_ROY.AZURE_EXT_STAGE/emp.json' 
(file_format => POC.SAIKOT_ROY.AZURE_JSON)
);


---------------------------- WE WILL GET ERROR AS COPY NOT SUPPORT JOIN
COPY INTO POC.SAIKOT_ROY.EMP_DEPT
FROM(
	SELECT
    E.$1::INT as "EMPLOYEE_ID",
    E.$2 || ' ' || E.$3 as "FULL_NAME",
    TO_DATE(E.$6, 'dd-MON-yy') as "HIRE_DATE",
    E.$8::FLOAT as "SALARY",
    E.$9::FLOAT as "COMMISSION_PCT",
    D.$2 as "DEPARTMENT_NAME"
	FROM '@POC.SAIKOT_ROY.AZURE_EXT_STAGE/employees.csv' E
	INNER JOIN '@POC.SAIKOT_ROY.AZURE_EXT_STAGE/departments.csv' D ON D.$1::INT = E.$11::INT
);


---------------------------- WORK AROUND IS USING INSERT INTO
INSERT INTO POC.SAIKOT_ROY.EMP_DEPT
SELECT
    E.$1::INT as "EMPLOYEE_ID",
    E.$2 || ' ' || E.$3 as "FULL_NAME",
    TO_DATE(E.$6, 'dd-MON-yy') as "HIRE_DATE",
    E.$8::FLOAT as "SALARY",
    E.$9::FLOAT as "COMMISSION_PCT",
    D.$2 as "DEPARTMENT_NAME"
FROM '@POC.SAIKOT_ROY.AZURE_EXT_STAGE/employees.csv' E
INNER JOIN '@POC.SAIKOT_ROY.AZURE_EXT_STAGE/departments.csv' D ON D.$1::INT = E.$11::INT;


---------------------------- GLOBAL AND LOCAL LOAD HISTORY
SELECT * FROM POC.INFORMATION_SCHEMA.LOAD_HISTORY;
SELECT * FROM SNOWFLAKE.INFORMATION_SCHEMA.LOAD_HISTORY;



---------------------------- TIMESTAMP OPERATIONS
SELECT
CURRENT_TIMESTAMP() AS SF_LOCAL_TS1,
CURRENT_TIMESTAMP::TIMESTAMP_LTZ AS SF_LOCAL_TS2,
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS SF_LOCAL_TS_WO_REGION;

SELECT
CONVERT_TIMEZONE('EST', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS EST_TS,
CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS UTC_TS,
CONVERT_TIMEZONE('America/New_York', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS US_TS,
TO_TIMESTAMP('11-MAY-24 01:57:10 PM', 'DD-MON-YY HH:MI:SS AM') AS CUSTOME_TS;



---------------------------- DATA UNLOADING FROM SNOWFLAKE
COPY INTO @POC.SAIKOT_ROY.AZURE_EXT_STAGE
FROM PILOT 
FILE_FORMAT = (
        TYPE = CSV,
        FIELD_OPTIONALLY_ENCLOSED_BY = '"',
        SKIP_HEADER = 1
)
OVERWRITE = TRUE;


---------------------------- SNOWFLAKE EXTERNAL TABLE OPERATIONS
CREATE OR REPLACE EXTERNAL TABLE POC.SAIKOT_ROY.EMP_EXT_AZ(
	EMPLOYEE_ID int AS (value:c1::int),
	NAME varchar AS replace((value:c2::varchar), '''', ''),
	SALARY number AS (value:c3::number),
	DEPARTMENT_ID number AS (value:c4::number),
	JOINING_DATE date AS TO_DATE(value:c5::varchar, '''YYYY-MM-DD''')
) 
LOCATION = @POC.SAIKOT_ROY.AZURE_EXT_STAGE 
PATTERN = 'ext_emp_\\d+\\.(txt|csv)' 
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1);


SELECT * FROM POC.SAIKOT_ROY.EMP_EXT_AZ ORDER BY EMPLOYEE_ID DESC;
ALTER EXTERNAL TABLE POC.SAIKOT_ROY.EMP_EXT_AZ refresh;


---------------------------- CACHE TESTING
select * from employees;
select * from departments;
select count(*) from employees;
select employee_id, first_name,erank from(
	select e.*,dense_rank() over(partition by department_id order by salary desc) as erank
	from employees e) where erank = 1;
    
	
---------------------------- TABLE TYPES
show tables;


---------------------------- TABLE CLONING
CREATE OR REPLACE TEMPORARY TABLE POC.SAIKOT_ROY.EMPLOYEES_TEMP CLONE EMPLOYEES;


---------------------------- TABLE SWAPPING
CREATE OR REPLACE TABLE POC.SAIKOT_ROY.EMP_DEPT_IT AS SELECT * FROM POC.SAIKOT_ROY.EMP_DEPT WHERE DEPARTMENT_NAME = 'IT';
CREATE OR REPLACE TABLE POC.SAIKOT_ROY.EMP_DEPT_EXECUTIVE AS SELECT * FROM POC.SAIKOT_ROY.EMP_DEPT WHERE DEPARTMENT_NAME = 'Executive';

SELECT 'EMP_DEPT_IT' AS TABLE_NAME,COUNT(*) FROM POC.SAIKOT_ROY.EMP_DEPT_IT
UNION
SELECT 'EMP_DEPT_EXECUTIVE' AS TABLE_NAME, COUNT(*) FROM POC.SAIKOT_ROY.EMP_DEPT_EXECUTIVE;
	
ALTER TABLE POC.SAIKOT_ROY.EMP_DEPT_IT SWAP WITH POC.SAIKOT_ROY.EMP_DEPT_EXECUTIVE;


SELECT 'EMP_DEPT_IT' AS TABLE_NAME,COUNT(*) FROM POC.SAIKOT_ROY.EMP_DEPT_IT
UNION
SELECT 'EMP_DEPT_EXECUTIVE' AS TABLE_NAME, COUNT(*) FROM POC.SAIKOT_ROY.EMP_DEPT_EXECUTIVE;




---------------------------- SAMPLING

select * from POC.SAIKOT_ROY.EMPLOYEES; -- #ROWS:107
select * from POC.SAIKOT_ROY.EMPLOYEES SAMPLE SYSTEM(1) SEED(10); -- #ROWS:4 (NORMALLY NEED TO APPLY ON LARGE TABLES)
select * From POC.SAIKOT_ROY.EMPLOYEES SAMPLE SYSTEM(1) SEED(10);


---------------------------- TASK
create or replace task POC.SAIKOT_ROY.HEARTBEAT_RESPONSE_TASK 
warehouse = 'WH_POC_APOLLO_XS' 
schedule = '3 minute' 
as
	INSERT INTO POC.SAIKOT_ROY.HEARTBEAT_RESPONSE(LOGNAME) VALUES('RESPONSE');

SHOW TASKS;
ALTER TASK POC.SAIKOT_ROY.HEARTBEAT_RESPONSE_TASK RESUME;
ALTER TASK POC.SAIKOT_ROY.HEARTBEAT_RESPONSE_TASK SUSPEND;


SELECT * FROM POC.SAIKOT_ROY.HEARTBEAT_RESPONSE;
	
	
---------------------------- STREAM
CREATE OR REPLACE STREAM POC.SAIKOT_ROY.HEARTBEAT_RESPONSE_STREAM ON TABLE POC.SAIKOT_ROY.HEARTBEAT_RESPONSE;
-- SINGLE STREAM DETAILS
DESC STREAM POC.SAIKOT_ROY.HEARTBEAT_RESPONSE_STREAM;
-- ALL STREAM DETAILS
SHOW STREAMS;
-- CDC
MERGE INTO POC.SAIKOT_ROY.HEARTBEAT_RESPONSE_STREAM_TGT TGT 
USING POC.SAIKOT_ROY.HEARTBEAT_RESPONSE_STREAM STM 
ON STM.ID = TGT.ID
WHEN MATCHED AND STM.METADATA$ACTION = 'INSERT' AND STM.METADATA$ISUPDATE = 'TRUE' THEN
UPDATE SET
    TGT.LOGNAME = STM.LOGNAME,
    TGT.RESPONSE_TS = STM.RESPONSE_TS
    WHEN MATCHED
    AND STM.METADATA$ACTION = 'DELETE'
    AND STM.METADATA$ISUPDATE = 'FALSE' THEN DELETE
WHEN NOT MATCHED AND STM.METADATA$ACTION = 'INSERT' AND STM.METADATA$ISUPDATE = 'FALSE' THEN
	INSERT(TGT.ID, TGT.LOGNAME, TGT.RESPONSE_TS)
	VALUES(STM.ID, STM.LOGNAME, STM.RESPONSE_TS);
	
	
	
SELECT * FROM POC.SAIKOT_ROY.HEARTBEAT_RESPONSE_STREAM_TGT;
SELECT * FROM POC.SAIKOT_ROY.HEARTBEAT_RESPONSE_STREAM;
SELECT * FROM POC.SAIKOT_ROY.HEARTBEAT_RESPONSE;



---------------------------- MATERIALIZED VIEW
CREATE OR REPLACE MATERIALIZED VIEW POC.SAIKOT_ROY.MV_EMPLOYEES 
CLUSTER BY (DEPARTMENT_ID) AS
SELECT
    DEPARTMENT_ID,
    MIN(SALARY) AS MIN_SAL,
    AVG(SALARY) AS AVG_SAL,
    MAX(SALARY) AS MAX_SAL,
    SUM(SALARY) AS TOTAL_SAL
FROM POC.SAIKOT_ROY.EMPLOYEES
GROUP BY DEPARTMENT_ID;

---------------------------- WHY RECLUSTERING IS REQUIRED?
ALTER TABLE POC.SAIKOT_ROY.MV_EMPLOYEES RESUME RECLUSTER;
SHOW MATERIALIZED VIEWS;
SELECT * FROM POC.SAIKOT_ROY.MV_EMPLOYEES order by TOTAL_SAL DESC;
ALTER MATERIALIZED VIEW POC.SAIKOT_ROY.MV_EMPLOYEES RESUME;



---------------------------- SEARCH OPTIMIZATON SERVICES
alter table POC.SAIKOT_ROY.EMPLOYEES add search optimization;
ALTER TABLE POC.SAIKOT_ROY.EMPLOYEES CLUSTER BY(DEPARTMENT_ID);
ALTER TABLE POC.SAIKOT_ROY.EMPLOYEES
SET DATA_RETENTION_TIME_IN_DAYS = 30;
SHOW TABLES;



---------------------------- DATA COMPRESSION
select employee_id, department_id, compress(salary, 'zlib') from POC.SAIKOT_ROY.EMPLOYEES;


---------------------------- DYNAMIC TABLE
create or replace table dep2023 as
SELECT * FROM departments
where department_id in (90, 80, 70, 60);

SELECT * FROM DEP2023;

create or replace dynamic table DEP2023_DYN 
TARGET_LAG = '1 minutes' 
WAREHOUSE = WH_POC_APOLLO_XS 
AS
SELECT
    D.DEPARTMENT_ID,
    D.DEPARTMENT_NAME,
    SUM(E.SALARY) AS DEPT_TOTALSAL
FROM DEP2023 D
LEFT JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY
    D.DEPARTMENT_ID,
    D.DEPARTMENT_NAME;
	
SELECT * FROM DEP2023_DYN;



/*  ALTER DYNAMIC TABLE DEP2023_DYN REFRESH; */

DELETE FROM DEP2023 where department_id = 70;

update DEP2023
set department_name = 'Admins'
where department_id = 60;

insert into DEP2023
values(200, 'IT', 103, 1400);




---------------------------- FUNCTION CREATION
CREATE OR REPLACE FUNCTION calculate_total_salary(salary FLOAT, commission_pct FLOAT) 
RETURNS FLOAT AS
$$
    salary + (salary * NVL(commission_pct, 0))
$$;

/* FUNCTION CALL */
SELECT EMPLOYEE_ID,DEPARTMENT_ID, SALARY, commission_pct, calculate_total_salary(salary,commission_pct)
FROM EMPLOYEES
WHERE commission_pct IS NOT NULL;



---------------------------- SP CREATION #1
CREATE OR REPLACE PROCEDURE POC.SAIKOT_ROY.get_department_salary_stats(dept_id INT)
RETURNS TABLE()
LANGUAGE SQL
AS
BEGIN
    LET results RESULTSET := (
        SELECT sum(salary) as total_salary, min(salary) as minimum_salary, max(salary) as maximum_salary, round(avg(salary),2) as average_salary
        FROM POC.SAIKOT_ROY.EMPLOYEES WHERE DEPARTMENT_ID = :dept_id);
    RETURN TABLE(results);
END;


CALL POC.SAIKOT_ROY.get_department_salary_stats(null);


---------------------------- SP CREATION #2
CREATE OR REPLACE PROCEDURE POC.SAIKOT_ROY.get_glassdoor_avg_rating()
RETURNS FLOAT
LANGUAGE SQL
AS
$$
DECLARE
    v_min_salary FLOAT;
    v_max_salary FLOAT;
    v_avg_salary FLOAT;
    v_result VARIANT;
    v_sum_salary INT;
BEGIN
    SELECT AVG(RATING) INTO v_sum_salary
    FROM POC.SAIKOT_ROY.EMPLOYEES
    WHERE DEPARTMENT_ID = :dept_id;

    RETURN v_sum_salary;
END;
$$;

select * from POC.SAIKOT_ROY.GLASSDOOR_REVIEW_RAW


----------------------------------------------------------------------------


-- USING LIMIT
SELECT * FROM POC.SAIKOT_ROY.employees ORDER BY SALARY DESC LIMIT 5;

-- USING ANALYTICAL FUCNTION (SNOWFLAKE)
SELECT * FROM POC.SAIKOT_ROY.employees 
QUALIFY DENSE_RANK() OVER (ORDER BY SALARY DESC) <= 5;

-- USING ANALYTICAL FUCNTION
SELECT * FROM (
    SELECT *, DENSE_RANK() OVER (ORDER BY SALARY DESC) AS RNK FROM POC.SAIKOT_ROY.employees
) WHERE RNK <=5;

-- WITHOUT ANALYTICAL
SELECT * FROM POC.SAIKOT_ROY.employees OQ
WHERE 5-1 >= (SELECT COUNT(EMPLOYEE_ID) FROM POC.SAIKOT_ROY.employees IQ WHERE OQ.SALARY < IQ.SALARY)
ORDER BY SALARY DESC;


-------------------------------------------------------------------------------------------

SELECT * FROM POC.SAIKOT_ROY.employees 
QUALIFY DENSE_RANK() OVER (PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC) =2 ;

SELECT * FROM (
    SELECT *, DENSE_RANK() OVER (PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC) AS RNK FROM POC.SAIKOT_ROY.employees
) WHERE RNK =2 ;

SELECT * FROM POC.SAIKOT_ROY.employees OQ
WHERE 2-1 = (SELECT COUNT(EMPLOYEE_ID) FROM POC.SAIKOT_ROY.employees IQ WHERE OQ.SALARY < IQ.SALARY AND OQ.DEPARTMENT_ID=IQ.DEPARTMENT_ID)
ORDER BY SALARY DESC;






SELECT * FROM POC.SAIKOT_ROY.TEST UNION SELECT * FROM POC.SAIKOT_ROY.TEST; -- SET UNION
SELECT * FROM POC.SAIKOT_ROY.TEST INTERSECT SELECT * FROM POC.SAIKOT_ROY.TEST; -- SET INTERSECT
SELECT * FROM POC.SAIKOT_ROY.TEST GROUP BY ALL; -- AGGREGATE FUNCTION
SELECT * FROM POC.SAIKOT_ROY.TEST QUALIFY ROW_NUMBER() OVER (PARTITION BY ID,NAME ORDER BY ID) = 1;  -- ANALYTICAL FUNCTION SNOWFLAEK QUALIFY
SELECT DISTINCT ID,NAME FROM TEST;
SELECT UNIQUE ID,NAME FROM TEST;   -- ORACLE



SELECT * FROM POC.SAIKOT_ROY.TEST GROUP BY ALL HAVING count(ID) = 1;
SELECT * FROM POC.SAIKOT_ROY.TEST 
MINUS
SELECT * FROM POC.SAIKOT_ROY.TEST QUALIFY ROW_NUMBER() OVER (PARTITION BY ID,NAME ORDER BY ID) = 2;



SELECT E.EMPLOYEE_ID,  E.MANAGER_ID FROM POC.SAIKOT_ROY.employees E LEFT JOIN POC.SAIKOT_ROY.employees M
ON E.MANAGER_ID = M.EMPLOYEE_ID WHERE E.MANAGER_ID is null; -- who dont have any manager
SELECT E.EMPLOYEE_ID,  E.MANAGER_ID FROM POC.SAIKOT_ROY.employees E JOIN POC.SAIKOT_ROY.employees M
ON E.MANAGER_ID = M.EMPLOYEE_ID;                            -- who have manager



CREATE OR REPLACE TABLE TEST2 AS SELECT * FROM TEST WHERE 1=1;
CREATE OR REPLACE TABLE TEST2 AS SELECT * FROM TEST WHERE 1=2;
CREATE OR REPLACE TABLE TEST2 CLONE TEST;   -- SNOWFLAKE ONLY
CREATE OR REPLACE TABLE TEST2 LIKE TEST;    -- SNOWFLAKE ONLY




SELECT * FROM POC.SAIKOT_ROY.employees
    WHERE MOD(EMPLOYEE_ID,2)=0; -- ASSUMING THERE IS SOME INTEGRER COLUMN FOR ODD/EVEN OPERATION
SELECT * FROM POC.SAIKOT_ROY.employees 
    QUALIFY MOD(ROW_NUMBER() OVER (ORDER BY 1),2)=0; --(SNOWFLAKE) ASSUMING THERE IS NO COLUMN FOR ODD/EVEN OPERATION




SELECT TABLE_NAME, ROW_COUNT FROM INFORMATION_SCHEMA.TABLES;




SELECT VALUE
FROM LATERAL SPLIT_TO_TABLE(ARRAY_TO_STRING(ARRAY_GENERATE_RANGE(1,11),','),',');


SELECT QUATER, COUNT(QUATER) FROM (
    SELECT 
    EMPLOYEE_ID,
    CASE 
    WHEN EXTRACT(MONTH FROM HIRE_DATE) IN (1,2,3) THEN 'Q1'
    WHEN EXTRACT(MONTH FROM HIRE_DATE) IN (4,5,6) THEN 'Q2'
    WHEN EXTRACT(MONTH FROM HIRE_DATE) IN (7,8,9) THEN 'Q3'
    WHEN EXTRACT(MONTH FROM HIRE_DATE) IN (10,11,12) THEN 'Q4'
    END AS QUATER
    FROM EMPLOYEES
) GROUP BY QUATER;



SELECT SUM(0), SUM(1), SUM(2) FROM EMPLOYEES;


CREATE OR REPLACE TABLE POC.SAIKOT_ROY.TEST(ID INT, NAME STRING);
INSERT INTO POC.SAIKOT_ROY.TEST VALUES (1,'A'),(2,'B'),(3,NULL),(NULL,NULL);
SELECT COUNT(*), COUNT('A'), COUNT(10), COUNT(-10), COUNT(NAME), COUNT(NULL)
FROM TEST;




SELECT 
    REGEXP_COUNT('SNOWFLAKE DATA ENGINEER','E') AS FREQ1, 
    LENGTH('SNOWFLAKE DATA ENGINEER')-LENGTH(REPLACE('SNOWFLAKE DATA ENGINEER','E','')) AS FREQ2;




CREATE OR REPLACE TABLE POC.SAIKOT_ROY.TEST(ID INT);
INSERT INTO POC.SAIKOT_ROY.TEST VALUES (1),(0),(1);

SELECT ID, CASE WHEN ID=1 THEN 0 ELSE 1 END AS MOD_ID FROM POC.SAIKOT_ROY.TEST;


SELECT LEVEL FROM (
    SELECT LEVEL, dummy 
    FROM (select 'X' dummy ) DUAL 
    CONNECT BY prior LEVEL <= 10
);


-- DEPARTMENT WISE MORE AVG SALARY EARNER
WITH CTE AS (
    SELECT DEPARTMENT_ID, ROUND(AVG(SALARY)) AS AVG_SAL FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID
)
SELECT E.EMPLOYEE_ID, E.SALARY, E.DEPARTMENT_ID, C.AVG_SAL 
FROM EMPLOYEES E, CTE C
WHERE E.DEPARTMENT_ID = C.DEPARTMENT_ID AND E.SALARY > C.AVG_SAL;


SELECT EMPLOYEE_ID, SALARY, DEPARTMENT_ID FROM EMPLOYEES E1
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES E2 WHERE E1.DEPARTMENT_ID=E2.DEPARTMENT_ID)
ORDER BY DEPARTMENT_ID;

SELECT COUNT(*) FROM EMPLOYEES;
SELECT * FROM EMPLOYEES
QUALIFY ROW_NUMBER() OVER(ORDER BY EMPLOYEE_ID ASC) <= (SELECT COUNT(*)/2 FROM EMPLOYEES);


select max(salary) from POC.SAIKOT_ROY.EMPLOYEES;  --24000
select max(salary) from POC.SAIKOT_ROY.EMPLOYEES WHERE SALARY < ( select max(salary) from POC.SAIKOT_ROY.EMPLOYEES); --17000
select max(salary) from POC.SAIKOT_ROY.EMPLOYEES WHERE SALARY < ( select max(salary) from POC.SAIKOT_ROY.EMPLOYEES WHERE SALARY < (select max(salary) from POC.SAIKOT_ROY.EMPLOYEES)); --14000


select salary from POC.SAIKOT_ROY.EMPLOYEES o
where 1-1 = (select count(employee_id) from POC.SAIKOT_ROY.EMPLOYEES i where i.salary > o.salary); --24000
select salary from POC.SAIKOT_ROY.EMPLOYEES o
where 2-1 = (select count(employee_id) from POC.SAIKOT_ROY.EMPLOYEES i where i.salary > o.salary); --17000



select employee_id, first_name||' '||last_name as full_name, department_id, hire_date from POC.SAIKOT_ROY.EMPLOYEES
qualify dense_rank() over (partition by department_id order by hire_date desc) = 1;


select m.first_name as manager_name, count(*)
from POC.SAIKOT_ROY.EMPLOYEES e, POC.SAIKOT_ROY.EMPLOYEES m
where e.manager_id = m.employee_id
group by m.first_name;


select * from POC.SAIKOT_ROY.EMPLOYEES
where extract(day from hire_date) < 5;



SELECT EMPLOYEE_ID, FIRST_NAME||LAST_NAME AS FULL_NAME, SALARY
FROM EMPLOYEES WHERE SALARY IN (SELECT MAX(SALARY) FROM EMPLOYEES) OR SALARY IN (SELECT MIN(SALARY) FROM EMPLOYEES);


with DEP_SAL(department_id, max_sal, min_sal) as (
    select department_id, max(salary) as max_sal, min(salary) as min_sal
    from POC.SAIKOT_ROY.EMPLOYEES group by DEPARTMENT_ID
)
select EMPLOYEE_ID, FIRST_NAME||LAST_NAME AS FULL_NAME, SALARY, E.DEPARTMENT_ID
from POC.SAIKOT_ROY.EMPLOYEES E, DEP_SAL D
where E.DEPARTMENT_ID = D.DEPARTMENT_ID and (E.salary = D.max_sal or E.salary = D.min_sal);



CREATE OR REPLACE TABLE TEST(ID INT);
INSERT INTO TEST VALUES(1),(2),(3),(4),(5);

DELETE FROM TEST WHERE ID = 4;

SELECT * FROM TEST AT(OFFSET => -60*3) --1,2,3,4,5
MINUS
SELECT * FROM TEST; --1,2,3,5



SELECT EXTRACT(MONTH FROM HIRE_DATE), TO_CHAR(HIRE_DATE, 'MON') AS MONTH, COUNT(*)
FROM EMPLOYEES GROUP BY EXTRACT(MONTH FROM HIRE_DATE), TO_CHAR(HIRE_DATE, 'MON')
ORDER BY 1;


SELECT EMPLOYEE_ID, DEPARTMENT_ID, SALARY, BUCKET FROM (
    SELECT *,NTILE(3) OVER(PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC) AS BUCKET FROM POC.SAIKOT_ROY.EMPLOYEES
) WHERE BUCKET = 2 ORDER BY EMPLOYEE_ID;


CREATE OR REPLACE TABLE LOGIN_STATS(ID INT, NAME STRING, LOGINDATE DATE);

INSERT INTO LOGIN_STATS VALUES
(101,'MIC','2021-08-21'),
(102,'JAM','2021-08-21'),
(103,'STE','2021-08-22'),
(104,'STE','2021-08-22'),
(105,'STE','2021-08-22'),
(106,'MIC','2021-08-23'),
(107,'MIC','2021-08-23'),
(108,'STE','2021-08-24'),
(109,'STE','2021-08-24'),
(110,'JAM','2021-08-25'),
(111,'JAM','2021-08-25'),
(112,'JAM','2021-08-26'),
(113,'JAM','2021-08-27');


SELECT DISTINCT NAME FROM (
    SELECT 
    NAME, CASE
            WHEN LEAD(NAME,1) OVER (ORDER BY ID) = NAME AND LEAD(NAME,2) OVER (ORDER BY ID) = NAME THEN 1
            ELSE 0
    END AS FLAG FROM POC.SAIKOT_ROY.LOGIN_STATS
) WHERE FLAG = 1; 



CREATE OR REPLACE TABLE TEST(ID INT, NAME STRING);
INSERT INTO TEST VALUES (1,'A'),(2,'B'),(3,'C'),(4,'D'),(5,'E');

SELECT ID,NAME,CASE
    WHEN MOD(ID,2)=1 THEN LEAD(NAME,1,NAME) OVER(ORDER BY ID)
    WHEN MOD(ID,2)=0 THEN LAG(NAME,1) OVER(ORDER BY ID)
    END AS MOD_NAME
FROM POC.SAIKOT_ROY.TEST;



create OR REPLACE table weather
(
id int,
city varchar(50),
temperature int,
day date
);

insert into weather values
(1, 'London', -1, '2021-01-01'),
(2, 'London', -2, '2021-01-02'),
(3, 'London', 4, '2021-01-03'),
(4, 'London', 1, '2021-01-04'),
(5, 'London', -2, '2021-01-05'),
(6, 'London', -5, '2021-01-06'),
(7, 'London', -7, '2021-01-07'),
(8, 'London', 5, '2021-01-08');


SELECT * FROM WEATHER;

SELECT * FROM (
    SELECT ID, CITY, TEMPERATURE, DAY, CASE
        WHEN TEMPERATURE<0 AND LEAD(TEMPERATURE,1) OVER(ORDER BY DAY) < 0 AND LEAD(TEMPERATURE,2) OVER(ORDER BY DAY) < 0 THEN 1
        WHEN TEMPERATURE<0 AND LEAD(TEMPERATURE,1) OVER(ORDER BY DAY) < 0 AND LAG(TEMPERATURE,1)  OVER(ORDER BY DAY) < 0 THEN 1
        WHEN TEMPERATURE<0 AND LAG(TEMPERATURE,1)  OVER(ORDER BY DAY) < 0 AND LAG(TEMPERATURE,2)  OVER(ORDER BY DAY) < 0 THEN 1
        ELSE 0
    END AS FLAG
    FROM POC.SAIKOT_ROY.WEATHER
) WHERE FLAG = 1;




SELECT * FROM TEST;

SELECT id FROM (
    SELECT id, LISTAGG(skill_set,',') WITHIN GROUP (ORDER BY skill_set) AS skill_list
    FROM POC.SAIKOT_ROY.TEST
    GROUP BY id
    ORDER BY id
) WHERE skill_list = 'SQL,powerbi,python';




CREATE OR REPLACE TABLE TEST(NAME STRING);
INSERT INTO TEST VALUES ('IND'),('RSA'),('AUS'),('ENG');
SELECT * FROM TEST;

WITH CTE AS (
    SELECT ROW_NUMBER() OVER (ORDER BY NAME ASC) AS SEQ, NAME
    FROM POC.SAIKOT_ROY.TEST
) SELECT T1.NAME, T2.NAME FROM CTE T1, CTE T2
WHERE T1.SEQ < T2.SEQ AND T1.NAME <> T2.NAME;



create or replace table test(id int, name string);

insert into test values
(1,'emp1'),(2,'emp2'),(3,'emp3'),(4,'emp4'),(5,'emp5'),(6,'emp6'),(7,'emp7'),(8,'emp8');

select * from test;

with cte as (
select id||' '||name as col1, ntile(4) over (order by id) as col2
from test
) select col2, listagg(col1,',') within group (order by col1)
from cte
group by col2
order by col2;





Create or replace Table test 
( 
CourseName string,
CourseCategory string,
Price int  
);

Insert into test  values('C', 'PROGRAMMING', 5000) ;
Insert into test  values('JAVA', 'PROGRAMMING', 6000) ;
Insert into test  values('PYTHON', 'PROGRAMMING', 8000) ;
Insert into test  values('PLACEMENT 100', 'INTERVIEWPREPARATION', 5000) ;

SELECT * FROM test; 

select * from test
pivot( sum(price) for coursecategory in ('PROGRAMMING','INTERVIEWPREPARATION'));


create or replace table test2 as
select
coursename,
sum(case when coursecategory='PROGRAMMING' then price end) as PROGRAMMING,
sum(case when coursecategory='INTERVIEWPREPARATION' then price end) as INTERVIEWPREPARATION
from test
group by coursename;


select * from test2;


select * from test2
unpivot(
    price for coursecategory in ("PROGRAMMING", "INTERVIEWPREPARATION")
);



create or replace table test(col1 int, col2 int, col3 int);
insert into test values
(100, 200, 300),
(200,300, 300),
(100, 200, 300);


select * from test;

select '100' as COL1, sum(regexp_count(col1||col2||col3, '100')) AS COL2 from test
UNION
SELECT '200' as COL1, sum(regexp_count(col1||col2||col3, '200')) AS COL2 from test
UNION
SELECT '300' as COL1, sum(regexp_count(col1||col2||col3, '300')) AS COL2 from test;


select regexp_replace('abcda','a','x',1,2) as col1 --replace 2nd 'a' value
union all
select regexp_replace('abcda','a','x',1) as col1
union all
select regexp_replace('abcda','a','x') as col1;